//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormControls_MVC5
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCountry
    {
        public string UserCountryID { get; set; }
        public string UserID { get; set; }
        public string CountryID { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual User User { get; set; }
    }
}
